# Database Service (Mysql)
db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_DATABASE: banco
    MYSQL_USER: usr_banco
    MYSQL_PASSWORD: usr_banco
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - db-data:/var/lib/mysql
